# Generated by Django 3.2.5 on 2021-08-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=12)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('file', models.FileField(upload_to='pdf_files/')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталоги',
            },
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=12)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('file', models.FileField(upload_to='pdf_files/')),
            ],
            options={
                'verbose_name': 'Электрическая схема',
                'verbose_name_plural': 'Электрические схемы',
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.PositiveIntegerField()),
                ('number', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=12)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('file', models.FileField(upload_to='pdf_files/')),
            ],
            options={
                'verbose_name': 'Рабочая инструкция',
                'verbose_name_plural': 'Рабочие инструкции',
            },
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=12)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('file', models.FileField(upload_to='pdf_files/')),
            ],
            options={
                'verbose_name': 'Мануал',
                'verbose_name_plural': 'Мануалы',
            },
        ),
    ]
