# Generated by Django 3.1.3 on 2021-08-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screw',
            name='assembly_place',
        ),
        migrations.AddField(
            model_name='screw',
            name='assembly_place_A_first',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='screw',
            name='assembly_place_A_second',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='screw',
            name='assembly_place_B_first',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='screw',
            name='assembly_place_B_second',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='screw',
            name='assembly_place_C_first',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='screw',
            name='assembly_place_C_second',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='screw',
            name='assembly_place_D',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='screw',
            name='assembly_place_H_first',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='screw',
            name='assembly_place_H_second',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='screw',
            name='assembly_place_H_third',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='screw',
            name='diameter',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='screw',
            name='length',
            field=models.PositiveIntegerField(),
        ),
    ]
