# Generated by Django 3.1.3 on 2021-08-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_screw_place_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screw',
            name='place_line',
        ),
        migrations.AlterField(
            model_name='screw',
            name='assembly_place',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='screw',
            name='strength',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
