# Generated by Django 3.1.3 on 2021-08-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_auto_20210811_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baan_id', models.CharField(max_length=50)),
                ('item_name', models.CharField(blank=True, max_length=50)),
                ('screw_thread', models.CharField(blank=True, max_length=5)),
                ('diameter', models.PositiveIntegerField(blank=True)),
                ('length', models.PositiveIntegerField(blank=True)),
                ('strength', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('iso', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=10)),
                ('assembly_place', models.CharField(max_length=10, unique=True)),
                ('warehouse_place', models.CharField(max_length=10)),
                ('file', models.FileField(blank=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиции',
            },
        ),
        migrations.DeleteModel(
            name='Screw',
        ),
    ]
