# Generated by Django 3.2.5 on 2021-08-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_auto_20210811_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='diameter',
        ),
        migrations.RemoveField(
            model_name='item',
            name='length',
        ),
        migrations.RemoveField(
            model_name='item',
            name='screw_thread',
        ),
        migrations.RemoveField(
            model_name='item',
            name='strength',
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default='   ', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
