# Generated by Django 3.1.3 on 2021-08-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CTX510', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='operation',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='operation',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='operation',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='manual',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='manual',
            name='operation',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
